-- Regression contract: sorting belongs only to Sort mode.
local path = "../addon/ShirsRaidBuilder/ShirsRaidBuilder.lua"
local file = assert(io.open(path, "rb"))
local source = file:read("*a")
file:close()

local finishStart = assert(string.find(source, "local function FinishExecute", 1, true))
local finishStop = assert(string.find(source, "local function StopQueue", finishStart, true))
local finishBody = string.sub(source, finishStart, finishStop - 1)

assert(not string.find(finishBody, "StartRaidSort", 1, true), "hire execution must not start raid sorting")
assert(string.find(source, "showBtn(mainFrame.sortBtn, sort)", 1, true), "Sort button must be visible only in Sort mode")
assert(string.find(source, "local function StartRaidSort", 1, true), "Sort mode must retain the paced raid sorter")
assert(string.find(source, "mainFrame.sortBtn", 1, true), "Sort mode must retain its Sort action")
assert(not string.find(source, "then legacy overwrite, then sort the raid", 1, true), "Hire Execute tooltip must not promise sorting")

local panelStart = assert(string.find(source, "local function StylePanelFrame", 1, true))
local panelStop = assert(string.find(source, "local function RegisterEscapeFrame", panelStart, true))
local panelBody = string.sub(source, panelStart, panelStop - 1)
assert(string.find(panelBody, "frame:EnableMouse(true)", 1, true), "submenu panel backgrounds must capture mouse input")
assert(string.find(panelBody, 'frame:SetScript("OnMouseDown"', 1, true), "submenu panels must start moving from their own mouse handler")
assert(string.find(panelBody, 'frame:SetScript("OnMouseUp"', 1, true), "submenu panels must stop moving from their own mouse handler")
assert(not string.find(panelBody, "dragHandle", 1, true), "submenu movement must not depend on a child drag handle that can miss mouse input")
assert(string.find(source, 'mainFrame:RegisterForDrag("LeftButton")', 1, true), "the main panel must be draggable")
assert(string.find(source, 'MakeButton(mainFrame,"New",88,168,-48', 1, true), "New must use the shared top-row grid")
assert(string.find(source, 'MakeButton(mainFrame,"Rename",88,260,-48', 1, true), "Rename must use the shared top-row grid")
assert(string.find(source, 'MakeButton(mainFrame,"Delete",88,352,-48', 1, true), "Delete must use the shared top-row grid")
assert(string.find(source, 'MakeButton(mainFrame,"Add Normal",88,444,-48', 1, true), "Add Normal must align to top-row slot four")
assert(string.find(source, 'MakeButton(mainFrame,"Add Legacy",88,536,-48', 1, true), "Add Legacy must align to top-row slot five")
assert(string.find(source, 'MakeButton(mainFrame,"Capture",88,444,-48', 1, true), "Capture must share Add Normal geometry")
assert(string.find(source, 'MakeButton(mainFrame,"Save",88,536,-48', 1, true), "Save must share Add Legacy geometry")
assert(string.find(source, 'MakeButton(mainFrame,"Sort Mode",88,628,-48', 1, true), "Mode switch must use top-row slot six")
assert(string.find(source, 'MakeButton(mainFrame,"Deny Rules",118,22,-76', 1, true), "bottom-row buttons must share one width")
assert(string.find(source, 'MakeButton(mainFrame,"Other Commands",118,144,-76', 1, true), "Other Commands must align to bottom-row slot two")
assert(string.find(source, 'MakeButton(mainFrame,"Preview",118,266,-76', 1, true), "Preview must align to bottom-row slot three")
assert(string.find(source, 'MakeButton(mainFrame,"Execute",118,388,-76', 1, true), "Execute must align to bottom-row slot four")
assert(string.find(source, 'MakeButton(mainFrame,"Whispers",118,388,-76', 1, true), "Whispers must share Execute geometry")
assert(string.find(source, 'MakeButton(mainFrame,"Stop",118,510,-76', 1, true), "Stop must align to bottom-row slot five")
assert(string.find(source, 'MakeButton(mainFrame,"Sort",118,632,-76', 1, true), "Sort must align to bottom-row slot six")
assert(string.find(source, 'MakeButton(mainFrame,"Capture",88,444,-48,C.RequestCaptureLayout)', 1, true), "Capture must route through overwrite confirmation")
assert(string.find(source, "This will overwrite the current sort profile", 1, true), "Capture confirmation must name the destructive effect")
assert(string.find(source, "Don't show this warning again for this character", 1, true), "Capture confirmation must offer a per-character opt-out")
assert(string.find(source, "C.PlanRaidOrderSwaps", 1, true), "Sort mode must check exact within-group order")
assert(string.find(source, "C.PlanRaidOrderRebuild", 1, true), "Sort mode must stage a wrong subgroup through an empty buffer")
assert(string.find(source, "SetRaidSubgroup(row.index, action.group)", 1, true), "Sort mode must execute each staged slot-order action by fresh name lookup")
assert(string.find(source, "orderActionAttempts > 3", 1, true), "Sort mode must bound failed staged actions")
assert(string.find(source, "orderProcessed", 1, true), "Sort mode must mark one completed pass and continue to later groups")
assert(string.find(source, 'return "order-partial"', 1, true), "Sort mode must report partial exact ordering after checking every group")
assert(string.find(source, 'line1:SetText(tostring(spawnNumber) .. " " .. name)', 1, true), "slot number and name must share one text run so low UI scales cannot overlap them")
assert(string.find(source, 'line2:SetText((CLASS_LABELS[classKey] or classKey) .. " " .. (ROLE_SHORT[entry.role] or entry.role or ""))', 1, true), "class and role must use the narrow single-space card label")
assert(string.find(source, 'b:SetPoint("TOPLEFT", previous, "BOTTOMLEFT", 0, -2)', 1, true), "context buttons must chain from the prior button for stable low-scale spacing")
assert(string.find(source, 'if type(DB.characterRoles) ~= "table" then DB.characterRoles = {} end', 1, true), "account DB must retain player roles by character")
assert(string.find(source, 'C.RememberCharacterRole(DB.characterRoles, live.charName, live.class, value)', 1, true), "changing a player role must persist it by character")
assert(string.find(source, 'C.RememberedCharacterRole(DB.characterRoles, you, class)', 1, true), "board refresh must restore the current character role")
assert(string.find(source, 'local function RefreshAbilitySuggestions(input, class, role)', 1, true), "deny autocomplete must receive both class and role")
assert(string.find(source, 'if role ~= "all" and not C.RoleAllowedForClass(class, role) then return end', 1, true), "deny autocomplete must reject invalid class-role pairs")
assert(string.find(source, '{"All Roles","Tank","Healer","Ranged DPS","Melee DPS"}', 1, true), "deny rules must offer a class-wide All Roles scope")
assert(string.find(source, "function C.ResetDenyRuleEditor", 1, true), "deny rules need one shared fresh-rule reset")
assert(not string.find(source, "settingsRuleIndex", 1, true), "deny editor must not keep a hidden edit target; the dropdowns alone decide where Add writes")
assert(string.find(source, "FindDenyRule(p.denyRules, role, class)", 1, true), "ability suggestions must follow the current dropdown selection")
assert(string.find(source, "function C.FindDenyRule", 1, true) or string.find(source, "C.FindDenyRule", 1, true), "deny rules must be found by role+class values resolved from the dropdowns")
assert(string.find(source, "FindDenyRule(EnsureDB().denyRules, role, class)", 1, true), "ability suggestions must follow the current dropdown selection")
local addStart = assert(string.find(source, 'local addAbility=MakeButton(settingsFrame,"Add Ability",86,214,-106,function()', 1, true))
local addStop = assert(string.find(source, "        end)", addStart, true))
local addBody = string.sub(source, addStart, addStop)
assert(string.find(addBody, "RoleValue(settingsRoleButton.label:GetText())", 1, true), "Add Ability must read Role from the dropdown at click time")
assert(string.find(addBody, "ClassValue(settingsClassButton.label:GetText())", 1, true), "Add Ability must read Class from the dropdown at click time")
assert(string.find(addBody, "C.RoleAllowedForClass(class,role)", 1, true), "Add Ability must reject invalid class-role pairs instead of creating unreachable rules")
assert(string.find(addBody, "FindDenyRule(p.denyRules, role, class)", 1, true), "Add Ability must append to the exact role+class rule or create it")
assert(not string.find(addBody, ".role=", 1, true), "adding an ability must never re-key an existing rule to a new role or class")
local denyRemoveStart = assert(string.find(source, 'MakeButton(row,"Remove",64,296,0,function()', 1, true))
local denyRemoveStop = assert(string.find(source, "        end)", denyRemoveStart, true))
local denyRemoveBody = string.sub(source, denyRemoveStart, denyRemoveStop)
assert(string.find(denyRemoveBody, "all[ri]==rule", 1, true), "deny Remove must match the rule by identity, not row position")
assert(string.find(denyRemoveBody, "table.remove(all,ri)", 1, true), "deny Remove must delete only its own rule")
assert(string.find(denyRemoveBody, "C.ResetDenyRuleEditor()", 1, true), "removing a deny rule must immediately enter fresh-rule mode")
assert(string.find(source, 'MakeButton(settingsFrame,"New",64,18,14,C.ResetDenyRuleEditor,true)', 1, true), "New and Remove must use the same deny editor reset")
assert(string.find(source, "C.AppendLegacyGroupMembers(C.KeepPresentCompanions(executeCompanionList, present), EnsureDB().entries, present)", 1, true), "group commands must include legacy board members the server companion list omits")
assert(string.find(source, "function C.EnsureDenyListScroll(host, spec)", 1, true), "deny lists share one five-row scroll factory")
assert(string.find(source, "if C.DenyListNeedsScrollbar(count) then", 1, true), "the deny scrollbar must stay hidden until five items")
assert(string.find(source, "C.EnsureDenyListScroll(denyFrame", 1, true), "extra denies must use the five-row viewport")
assert(string.find(source, "C.EnsureDenyListScroll(settingsFrame", 1, true), "deny rules must use the five-row viewport")
assert(string.find(source, "C.DENY_LIST_VISIBLE_ROWS", 1, true), "deny list height must stay pinned to five visible rows")
assert(string.find(source, 'if type(ShirsRaidBuilderDB) ~= "table" then ShirsRaidBuilderDB = {} end', 1, true), "BindAccountDB must create the SavedVariable global, never return without binding; a missing global means logout saves nil and profiles vanish")

print("Shir's Raid Builder mode contract tests: PASS")
