-- Regression contract: sorting belongs only to Sort mode.
local path = "../addon/ShirsRaidBuilder/ShirsRaidBuilder.lua"
local file = assert(io.open(path, "rb"))
local source = file:read("*a")
file:close()

local finishStart = assert(string.find(source, "local function FinishExecute", 1, true))
local finishStop = assert(string.find(source, "local function StopQueue", finishStart, true))
local finishBody = string.sub(source, finishStart, finishStop - 1)

assert(not string.find(finishBody, "StartRaidSort", 1, true), "hire execution must not start raid sorting")
assert(string.find(source, "showBtn(mainFrame.sortBtn, sort)", 1, true), "Sort button must be visible only in Sort mode")
assert(string.find(source, "local function StartRaidSort", 1, true), "Sort mode must retain the paced raid sorter")
assert(string.find(source, "mainFrame.sortBtn", 1, true), "Sort mode must retain its Sort action")
assert(not string.find(source, "then legacy overwrite, then sort the raid", 1, true), "Hire Execute tooltip must not promise sorting")

local panelStart = assert(string.find(source, "local function StylePanelFrame", 1, true))
local panelStop = assert(string.find(source, "local function RegisterEscapeFrame", panelStart, true))
local panelBody = string.sub(source, panelStart, panelStop - 1)
assert(string.find(panelBody, "frame:EnableMouse(true)", 1, true), "submenu panel backgrounds must capture mouse input")
assert(string.find(source, 'MakeButton(mainFrame,"New",88,168,-48', 1, true), "New must use the shared top-row grid")
assert(string.find(source, 'MakeButton(mainFrame,"Rename",88,260,-48', 1, true), "Rename must use the shared top-row grid")
assert(string.find(source, 'MakeButton(mainFrame,"Delete",88,352,-48', 1, true), "Delete must use the shared top-row grid")
assert(string.find(source, 'MakeButton(mainFrame,"Add Normal",88,444,-48', 1, true), "Add Normal must align to top-row slot four")
assert(string.find(source, 'MakeButton(mainFrame,"Add Legacy",88,536,-48', 1, true), "Add Legacy must align to top-row slot five")
assert(string.find(source, 'MakeButton(mainFrame,"Capture",88,444,-48', 1, true), "Capture must share Add Normal geometry")
assert(string.find(source, 'MakeButton(mainFrame,"Save",88,536,-48', 1, true), "Save must share Add Legacy geometry")
assert(string.find(source, 'MakeButton(mainFrame,"Sort Mode",88,628,-48', 1, true), "Mode switch must use top-row slot six")
assert(string.find(source, 'MakeButton(mainFrame,"Deny Rules",118,22,-76', 1, true), "bottom-row buttons must share one width")
assert(string.find(source, 'MakeButton(mainFrame,"Other Commands",118,144,-76', 1, true), "Other Commands must align to bottom-row slot two")
assert(string.find(source, 'MakeButton(mainFrame,"Preview",118,266,-76', 1, true), "Preview must align to bottom-row slot three")
assert(string.find(source, 'MakeButton(mainFrame,"Execute",118,388,-76', 1, true), "Execute must align to bottom-row slot four")
assert(string.find(source, 'MakeButton(mainFrame,"Whispers",118,388,-76', 1, true), "Whispers must share Execute geometry")
assert(string.find(source, 'MakeButton(mainFrame,"Stop",118,510,-76', 1, true), "Stop must align to bottom-row slot five")
assert(string.find(source, 'MakeButton(mainFrame,"Sort",118,632,-76', 1, true), "Sort must align to bottom-row slot six")
assert(string.find(source, 'MakeButton(mainFrame,"Capture",88,444,-48,C.RequestCaptureLayout)', 1, true), "Capture must route through overwrite confirmation")
assert(string.find(source, "This will overwrite the current sort profile", 1, true), "Capture confirmation must name the destructive effect")
assert(string.find(source, "Don't show this warning again for this character", 1, true), "Capture confirmation must offer a per-character opt-out")
assert(string.find(source, "C.PlanRaidOrderSwaps", 1, true), "Sort mode must check exact within-group order")
assert(string.find(source, "C.PlanRaidOrderRebuild", 1, true), "Sort mode must stage a wrong subgroup through an empty buffer")
assert(string.find(source, "SetRaidSubgroup(row.index, action.group)", 1, true), "Sort mode must execute each staged slot-order action by fresh name lookup")
assert(string.find(source, "orderActionAttempts > 3", 1, true), "Sort mode must bound failed staged actions")
assert(string.find(source, "orderProcessed", 1, true), "Sort mode must mark one completed pass and continue to later groups")
assert(string.find(source, 'return "order-partial"', 1, true), "Sort mode must report partial exact ordering after checking every group")

print("Shir's Raid Builder mode contract tests: PASS")
