-- Vanilla 1.12 castable class abilities only.
-- Trainer spells plus talent-granted action-bar spells. No talent passives,
-- ranks, effects, riding, or later-expansion skills.
ShirsRaidBuilderAbilities = {
    warrior = {
        "Battle Shout",
        "Battle Stance",
        "Berserker Rage",
        "Berserker Stance",
        "Bloodrage",
        "Bloodthirst",
        "Challenging Shout",
        "Charge",
        "Cleave",
        "Concussion Blow",
        "Death Wish",
        "Defensive Stance",
        "Demoralizing Shout",
        "Disarm",
        "Execute",
        "Hamstring",
        "Heroic Strike",
        "Intercept",
        "Intimidating Shout",
        "Last Stand",
        "Mocking Blow",
        "Mortal Strike",
        "Overpower",
        "Piercing Howl",
        "Pummel",
        "Recklessness",
        "Rend",
        "Retaliation",
        "Revenge",
        "Shield Bash",
        "Shield Block",
        "Shield Slam",
        "Shield Wall",
        "Slam",
        "Sunder Armor",
        "Sweeping Strikes",
        "Taunt",
        "Thunder Clap",
        "Whirlwind",
    },
    paladin = {
        "Blessing of Freedom",
        "Blessing of Kings",
        "Blessing of Light",
        "Blessing of Might",
        "Blessing of Protection",
        "Blessing of Sacrifice",
        "Blessing of Salvation",
        "Blessing of Sanctuary",
        "Blessing of Wisdom",
        "Cleanse",
        "Concentration Aura",
        "Consecration",
        "Devotion Aura",
        "Divine Favor",
        "Divine Intervention",
        "Divine Protection",
        "Divine Shield",
        "Exorcism",
        "Fire Resistance Aura",
        "Flash of Light",
        "Frost Resistance Aura",
        "Greater Blessing of Kings",
        "Greater Blessing of Light",
        "Greater Blessing of Might",
        "Greater Blessing of Salvation",
        "Greater Blessing of Sanctuary",
        "Greater Blessing of Wisdom",
        "Hammer of Justice",
        "Hammer of Wrath",
        "Holy Light",
        "Holy Shield",
        "Holy Shock",
        "Holy Wrath",
        "Judgement",
        "Lay on Hands",
        "Purify",
        "Redemption",
        "Repentance",
        "Retribution Aura",
        "Righteous Fury",
        "Sanctity Aura",
        "Seal of Command",
        "Seal of Justice",
        "Seal of Light",
        "Seal of Righteousness",
        "Seal of Wisdom",
        "Sense Undead",
        "Shadow Resistance Aura",
        "Summon Charger",
        "Summon Warhorse",
        "Turn Undead",
    },
    hunter = {
        "Aimed Shot",
        "Arcane Shot",
        "Aspect of the Beast",
        "Aspect of the Cheetah",
        "Aspect of the Hawk",
        "Aspect of the Monkey",
        "Aspect of the Pack",
        "Aspect of the Wild",
        "Auto Shot",
        "Beast Lore",
        "Bestial Wrath",
        "Call Pet",
        "Concussive Shot",
        "Counterattack",
        "Deterrence",
        "Disengage",
        "Dismiss Pet",
        "Distracting Shot",
        "Eagle Eye",
        "Explosive Trap",
        "Eyes of the Beast",
        "Feed Pet",
        "Feign Death",
        "Flare",
        "Freezing Trap",
        "Frost Trap",
        "Hunter's Mark",
        "Immolation Trap",
        "Intimidation",
        "Mend Pet",
        "Mongoose Bite",
        "Multi-Shot",
        "Rapid Fire",
        "Raptor Strike",
        "Revive Pet",
        "Scare Beast",
        "Scatter Shot",
        "Scorpid Sting",
        "Serpent Sting",
        "Tame Beast",
        "Track Beasts",
        "Track Demons",
        "Track Dragonkin",
        "Track Elementals",
        "Track Giants",
        "Track Hidden",
        "Track Humanoids",
        "Track Undead",
        "Tranquilizing Shot",
        "Trueshot Aura",
        "Viper Sting",
        "Volley",
        "Wing Clip",
        "Wyvern Sting",
    },
    rogue = {
        "Adrenaline Rush",
        "Ambush",
        "Backstab",
        "Blade Flurry",
        "Blind",
        "Cheap Shot",
        "Cold Blood",
        "Detect Traps",
        "Disarm Trap",
        "Distract",
        "Evasion",
        "Eviscerate",
        "Expose Armor",
        "Feint",
        "Garrote",
        "Ghostly Strike",
        "Gouge",
        "Hemorrhage",
        "Kick",
        "Kidney Shot",
        "Pick Lock",
        "Pick Pocket",
        "Preparation",
        "Premeditation",
        "Riposte",
        "Rupture",
        "Sap",
        "Sinister Strike",
        "Slice and Dice",
        "Sprint",
        "Stealth",
        "Vanish",
    },
    priest = {
        "Abolish Disease",
        "Cure Disease",
        "Desperate Prayer",
        "Devouring Plague",
        "Dispel Magic",
        "Divine Spirit",
        "Elune's Grace",
        "Fade",
        "Fear Ward",
        "Feedback",
        "Flash Heal",
        "Greater Heal",
        "Heal",
        "Hex of Weakness",
        "Holy Fire",
        "Holy Nova",
        "Inner Fire",
        "Inner Focus",
        "Lesser Heal",
        "Levitate",
        "Lightwell",
        "Mana Burn",
        "Mind Blast",
        "Mind Control",
        "Mind Flay",
        "Mind Soothe",
        "Mind Vision",
        "Power Infusion",
        "Power Word: Fortitude",
        "Power Word: Shield",
        "Prayer of Fortitude",
        "Prayer of Healing",
        "Prayer of Shadow Protection",
        "Prayer of Spirit",
        "Psychic Scream",
        "Renew",
        "Resurrection",
        "Shackle Undead",
        "Shadow Protection",
        "Shadow Word: Pain",
        "Shadowform",
        "Shadowguard",
        "Silence",
        "Smite",
        "Starshards",
        "Touch of Weakness",
        "Vampiric Embrace",
    },
    shaman = {
        "Ancestral Spirit",
        "Astral Recall",
        "Chain Heal",
        "Chain Lightning",
        "Disease Cleansing Totem",
        "Earth Shock",
        "Earthbind Totem",
        "Elemental Mastery",
        "Far Sight",
        "Fire Nova Totem",
        "Fire Resistance Totem",
        "Flame Shock",
        "Flametongue Totem",
        "Flametongue Weapon",
        "Frost Resistance Totem",
        "Frost Shock",
        "Frostbrand Weapon",
        "Ghost Wolf",
        "Grace of Air Totem",
        "Grounding Totem",
        "Healing Stream Totem",
        "Healing Wave",
        "Lesser Healing Wave",
        "Lightning Bolt",
        "Lightning Shield",
        "Magma Totem",
        "Mana Spring Totem",
        "Mana Tide Totem",
        "Nature Resistance Totem",
        "Nature's Swiftness",
        "Purge",
        "Reincarnation",
        "Rockbiter Weapon",
        "Searing Totem",
        "Sentry Totem",
        "Stoneclaw Totem",
        "Stoneskin Totem",
        "Stormstrike",
        "Strength of Earth Totem",
        "Tranquil Air Totem",
        "Tremor Totem",
        "Water Breathing",
        "Water Walking",
        "Windfury Totem",
        "Windfury Weapon",
        "Windwall Totem",
    },
    mage = {
        "Amplify Magic",
        "Arcane Brilliance",
        "Arcane Explosion",
        "Arcane Intellect",
        "Arcane Missiles",
        "Arcane Power",
        "Blast Wave",
        "Blink",
        "Blizzard",
        "Cold Snap",
        "Combustion",
        "Cone of Cold",
        "Conjure Food",
        "Conjure Mana Agate",
        "Conjure Mana Citrine",
        "Conjure Mana Jade",
        "Conjure Mana Ruby",
        "Conjure Water",
        "Counterspell",
        "Dampen Magic",
        "Detect Magic",
        "Evocation",
        "Fire Blast",
        "Fire Ward",
        "Fireball",
        "Flamestrike",
        "Frost Armor",
        "Frost Nova",
        "Frost Ward",
        "Frostbolt",
        "Ice Armor",
        "Ice Barrier",
        "Ice Block",
        "Mage Armor",
        "Mana Shield",
        "Polymorph",
        "Polymorph: Pig",
        "Polymorph: Turtle",
        "Portal: Darnassus",
        "Portal: Ironforge",
        "Portal: Orgrimmar",
        "Portal: Stormwind",
        "Portal: Thunder Bluff",
        "Portal: Undercity",
        "Presence of Mind",
        "Pyroblast",
        "Remove Lesser Curse",
        "Scorch",
        "Slow Fall",
        "Teleport: Darnassus",
        "Teleport: Ironforge",
        "Teleport: Orgrimmar",
        "Teleport: Stormwind",
        "Teleport: Thunder Bluff",
        "Teleport: Undercity",
    },
    warlock = {
        "Banish",
        "Conflagrate",
        "Corruption",
        "Create Firestone",
        "Create Healthstone",
        "Create Soulstone",
        "Create Spellstone",
        "Curse of Agony",
        "Curse of Doom",
        "Curse of Recklessness",
        "Curse of Shadow",
        "Curse of the Elements",
        "Curse of Tongues",
        "Curse of Weakness",
        "Dark Pact",
        "Death Coil",
        "Demon Armor",
        "Demon Skin",
        "Demonic Sacrifice",
        "Detect Greater Invisibility",
        "Detect Invisibility",
        "Detect Lesser Invisibility",
        "Drain Life",
        "Drain Mana",
        "Drain Soul",
        "Enslave Demon",
        "Eye of Kilrogg",
        "Fear",
        "Fel Domination",
        "Health Funnel",
        "Hellfire",
        "Howl of Terror",
        "Immolate",
        "Inferno",
        "Life Tap",
        "Rain of Fire",
        "Ritual of Doom",
        "Ritual of Summoning",
        "Searing Pain",
        "Sense Demons",
        "Shadow Bolt",
        "Shadow Ward",
        "Shadowburn",
        "Siphon Life",
        "Soul Fire",
        "Soul Link",
        "Summon Dreadsteed",
        "Summon Felhunter",
        "Summon Felsteed",
        "Summon Imp",
        "Summon Succubus",
        "Summon Voidwalker",
        "Unending Breath",
    },
    druid = {
        "Abolish Poison",
        "Aquatic Form",
        "Barkskin",
        "Bash",
        "Bear Form",
        "Cat Form",
        "Challenging Roar",
        "Claw",
        "Cower",
        "Cure Poison",
        "Dash",
        "Demoralizing Roar",
        "Dire Bear Form",
        "Enrage",
        "Entangling Roots",
        "Faerie Fire",
        "Faerie Fire (Feral)",
        "Feral Charge",
        "Ferocious Bite",
        "Frenzied Regeneration",
        "Gift of the Wild",
        "Growl",
        "Healing Touch",
        "Hibernate",
        "Hurricane",
        "Innervate",
        "Insect Swarm",
        "Mark of the Wild",
        "Maul",
        "Moonfire",
        "Moonkin Form",
        "Nature's Grasp",
        "Nature's Swiftness",
        "Omen of Clarity",
        "Pounce",
        "Prowl",
        "Rake",
        "Ravage",
        "Rebirth",
        "Regrowth",
        "Rejuvenation",
        "Remove Curse",
        "Rip",
        "Shred",
        "Soothe Animal",
        "Starfire",
        "Swiftmend",
        "Swipe",
        "Teleport: Moonglade",
        "Thorns",
        "Tiger's Fury",
        "Track Humanoids",
        "Tranquility",
        "Travel Form",
        "Wrath",
    },
}
